# See https://docs.blender.org/api/main/extensions.html
schema_version = "1.0.0"
id = "macblend"
name = "MacBlend"
tagline = "Calibrate colors in your scene using a Macbeth chart"
type = "add-on"
maintainer = "Manuel Houben"
version = "1.0.1"
website = "https://github.com/ManuelHouben/macblend"
blender_version_min = "4.2.0"
tags = ["Compositing", "Pipeline"]
license = ["SPDX:GPL-3.0-or-later"]
copyright = [
	"2024 Manuel Houben",
	"2013-2021 Colour Developers",
]

[permissions]
files = "Read color data and write LUTs to user-selected folders"

[build]
paths = [
	"__init__.py",
	"calibration.py",
	"colorspaces.py",
	"core.py",
	"LICENSE",
	"lut_writer.py",
	"mmColorTarget_colorspace_transforms.json",
	"sampling.py",
	"THIRD_PARTY_NOTICES.md",
]
