# See https://docs.blender.org/api/main/extensions.html
schema_version = "1.0.0"
id = "macblend"
name = "MacBlend"
tagline = "Calibrate colors in your scene using a Macbeth chart"
type = "add-on"
maintainer = "Manuel Houben"
version = "3.2.0"
website = "https://manuelhouben.github.io/macblend/"
support = "https://github.com/ManuelHouben/macblend/issues/new?template=bug_report.md"
blender_version_min = "4.2.0"
tags = ["Compositing", "Pipeline"]
license = ["SPDX:GPL-3.0-or-later"]
copyright = [
	"2024 Manuel Houben",
	"2013-2021 Colour Developers",
]

[permissions]
files = "Read color data and write LUTs to user-selected folders"

[build]
paths_exclude_pattern = [
	"__pycache__/",
	"/.git/",
	".*",
	"/*.zip",
]
